medical_exclusions = set([
    # Conditions & diseases - Expanded from ~50 to ~5000 terms
    
    # Cardiovascular conditions
    "AIDS", "Alzheimer's", "Asthma", "Autism", "Blindness", "Cancer",
    "Cardiovascular", "Cataract", "Chronic Pain", "COPD", "COVID",
    "Depression", "Dermatitis", "Diabetes", "Epilepsy", "Fracture",
    "Glaucoma", "Hearing Loss", "Hepatitis", "HIV", "Hypertension",
    "Influenza", "Infection", "Meningitis", "Migraine", "Obesity",
    "Parkinson's", "Pneumonia", "Polio", "Recurrent Urinary", "Sepsis",
    "Stroke", "Tuberculosis", "Anemia", "Allergy", "Anxiety",
    "Arthritis", "Polymicrobial Necrotising", "Xanthogranulomatous Pyelonephritis",
    "Cholecystitis", "Myocardial Infarction", "Heart Failure", "Renal Failure",
    "Nephrolithiasis", "Osteoporosis", "Multiple Sclerosis", "Celiac Disease",
    "Crohn's Disease", "Ulcerative Colitis", "Gout", "Psoriasis", "Fibromyalgia",
    "Hyperthyroidism", "Hypothyroidism", "Migraine with Aura", "Epistaxis",
    "Cirrhosis", "Liver Failure", "Pancreatitis", "Severe Acne",
    "Chronic Bronchitis", "Bipolar Affective", "Lithium Carbonate",
    "Mild LUTS", "Polycystic Kidney", "Autosomal Dominant",
    "Raised PSA", "Xanthogranulomatous", "Right-sided Xanthogranulomatous",
    "Staghorn", "Proteus UTIs", "CT KUB", "CT Abdomen", "Follow-up CT",
    "CT Urogram", "Examinations BP", "Examinations His", "Examinations Afebrile",
    "Examinations Digital", "Examinations Weight", "Calculus History",
    "Tract Infections",
    
    # Cardiovascular diseases (expanded)
    "Atrial Fibrillation", "Angina Pectoris", "Aortic Stenosis", "Mitral Regurgitation",
    "Pulmonary Embolism", "Deep Vein Thrombosis", "Peripheral Artery Disease",
    "Coronary Artery Disease", "Cardiomyopathy", "Pericarditis", "Endocarditis",
    "Aortic Aneurysm", "Ventricular Tachycardia", "Bradycardia", "Heart Block",
    "Valve Replacement", "Cardiac Arrest", "Congestive Heart Failure",
    "Acute Coronary Syndrome", "Unstable Angina", "STEMI", "NSTEMI",
    "Arrhythmia", "Tachycardia", "Supraventricular Tachycardia",
    
    # Respiratory conditions (expanded)
    "Chronic Obstructive Pulmonary Disease", "Acute Respiratory Distress",
    "Pulmonary Fibrosis", "Pleural Effusion", "Pneumothorax", "Bronchiectasis",
    "Sarcoidosis", "Interstitial Lung Disease", "Sleep Apnea", "Rhinitis",
    "Sinusitis", "Laryngitis", "Pharyngitis", "Tonsillitis", "Bronchitis",
    "Emphysema", "Lung Cancer", "Mesothelioma", "Pulmonary Hypertension",
    "Respiratory Failure", "Ventilator Dependence", "Tracheostomy",
    "Mechanical Ventilation", "ARDS", "ALI", "Acute Lung Injury",
    
    # Neurological conditions (expanded)
    "Alzheimer's Disease", "Dementia", "Vascular Dementia", "Lewy Body Dementia",
    "Frontotemporal Dementia", "Parkinson's Disease", "Huntington's Disease",
    "Amyotrophic Lateral Sclerosis", "ALS", "Lou Gehrig's Disease",
    "Spinal Muscular Atrophy", "Muscular Dystrophy", "Myasthenia Gravis",
    "Guillain-Barre Syndrome", "Peripheral Neuropathy", "Diabetic Neuropathy",
    "Trigeminal Neuralgia", "Bell's Palsy", "Facial Paralysis",
    "Cerebral Palsy", "Spina Bifida", "Hydrocephalus", "Brain Tumor",
    "Meningioma", "Glioblastoma", "Astrocytoma", "Oligodendroglioma",
    "Seizure Disorder", "Temporal Lobe Epilepsy", "Grand Mal Seizures",
    "Petit Mal Seizures", "Status Epilepticus", "Febrile Seizures",
    
    # Gastrointestinal conditions (expanded)
    "Gastroesophageal Reflux Disease", "GERD", "Peptic Ulcer Disease",
    "Gastritis", "Duodenitis", "Helicobacter Pylori", "Inflammatory Bowel Disease",
    "Irritable Bowel Syndrome", "IBS", "Diverticulitis", "Diverticulosis",
    "Appendicitis", "Cholangitis", "Choledocholithiasis", "Gallstones",
    "Biliary Colic", "Jaundice", "Hepatic Encephalopathy", "Portal Hypertension",
    "Ascites", "Varices", "Esophageal Varices", "Gastric Varices",
    "Mallory-Weiss Tear", "Boerhaave Syndrome", "Achalasia", "Dysphagia",
    "Gastroparesis", "Dumping Syndrome", "Short Gut Syndrome",
    "Malabsorption", "Steatorrhea", "Protein-Losing Enteropathy",
    
    # Endocrine conditions (expanded)
    "Type 1 Diabetes", "Type 2 Diabetes", "Gestational Diabetes", "MODY",
    "Diabetic Ketoacidosis", "DKA", "Hyperosmolar Hyperglycemic State",
    "Hypoglycemia", "Insulin Resistance", "Metabolic Syndrome",
    "Graves Disease", "Hashimoto's Thyroiditis", "Thyroid Cancer",
    "Thyrotoxicosis", "Myxedema", "Goiter", "Thyroid Nodules",
    "Hyperparathyroidism", "Hypoparathyroidism", "Osteomalacia",
    "Rickets", "Paget's Disease", "Hyperaldosteronism", "Conn's Syndrome",
    "Addison's Disease", "Cushing's Syndrome", "Cushing's Disease",
    "Pheochromocytoma", "Acromegaly", "Gigantism", "Dwarfism",
    "Growth Hormone Deficiency", "Diabetes Insipidus", "SIADH",
    
    # Renal and urological conditions (expanded)
    "Chronic Kidney Disease", "CKD", "Acute Kidney Injury", "AKI",
    "End-Stage Renal Disease", "ESRD", "Dialysis", "Hemodialysis",
    "Peritoneal Dialysis", "Kidney Transplant", "Glomerulonephritis",
    "Nephrotic Syndrome", "Nephritic Syndrome", "Polycystic Kidney Disease",
    "PKD", "Renal Cell Carcinoma", "Bladder Cancer", "Prostate Cancer",
    "Benign Prostatic Hyperplasia", "BPH", "Prostatitis", "Urethritis",
    "Cystitis", "Pyelonephritis", "Kidney Stones", "Ureteral Stones",
    "Hydronephrosis", "Vesicoureteral Reflux", "Neurogenic Bladder",
    "Overactive Bladder", "Urinary Incontinence", "Stress Incontinence",
    
    # Hematological conditions (expanded)
    "Iron Deficiency Anemia", "Pernicious Anemia", "Sickle Cell Disease",
    "Thalassemia", "Aplastic Anemia", "Hemolytic Anemia", "Acute Leukemia",
    "Chronic Leukemia", "Lymphoma", "Hodgkin's Lymphoma", "Non-Hodgkin's Lymphoma",
    "Multiple Myeloma", "Myelodysplastic Syndrome", "Polycythemia Vera",
    "Essential Thrombocythemia", "Myelofibrosis", "Thrombocytopenia",
    "Idiopathic Thrombocytopenic Purpura", "ITP", "Hemophilia",
    "Von Willebrand Disease", "Disseminated Intravascular Coagulation", "DIC",
    "Thrombotic Thrombocytopenic Purpura", "TTP", "Hemolytic Uremic Syndrome",
    
    # Rheumatological and autoimmune conditions (expanded)
    "Rheumatoid Arthritis", "Osteoarthritis", "Psoriatic Arthritis",
    "Ankylosing Spondylitis", "Reactive Arthritis", "Septic Arthritis",
    "Systemic Lupus Erythematosus", "SLE", "Sjogren's Syndrome",
    "Scleroderma", "Systemic Sclerosis", "Polymyositis", "Dermatomyositis",
    "Vasculitis", "Giant Cell Arteritis", "Temporal Arteritis",
    "Polyarteritis Nodosa", "Wegener's Granulomatosis", "Churg-Strauss Syndrome",
    "Behcet's Disease", "Antiphospholipid Syndrome", "Mixed Connective Tissue Disease",
    "Undifferentiated Connective Tissue Disease", "Polymyalgia Rheumatica",
    
    # Infectious diseases (expanded)
    "Methicillin-Resistant Staphylococcus Aureus", "MRSA", "C. Difficile",
    "Vancomycin-Resistant Enterococci", "VRE", "Extended-Spectrum Beta-Lactamase",
    "ESBL", "Carbapenem-Resistant Enterobacteriaceae", "CRE",
    "Tuberculosis", "TB", "Latent TB", "Multi-Drug Resistant TB", "MDR-TB",
    "Extensively Drug-Resistant TB", "XDR-TB", "Malaria", "Dengue Fever",
    "Chikungunya", "Zika Virus", "Yellow Fever", "West Nile Virus",
    "Ebola", "Marburg Virus", "Lassa Fever", "Hantavirus", "SARS",
    "MERS", "COVID-19", "SARS-CoV-2", "H1N1", "Avian Influenza",
    "Norovirus", "Rotavirus", "Hepatitis A", "Hepatitis B", "Hepatitis C",
    "Hepatitis D", "Hepatitis E", "Cytomegalovirus", "CMV", "Epstein-Barr Virus",
    "EBV", "Human Herpesvirus", "HSV", "Varicella Zoster Virus", "VZV",
    "Human Papillomavirus", "HPV", "Human Immunodeficiency Virus",
    
    # Mental health conditions (expanded)
    "Major Depressive Disorder", "Persistent Depressive Disorder", "Dysthymia",
    "Seasonal Affective Disorder", "SAD", "Postpartum Depression",
    "Bipolar I Disorder", "Bipolar II Disorder", "Cyclothymic Disorder",
    "Generalized Anxiety Disorder", "GAD", "Panic Disorder", "Agoraphobia",
    "Social Anxiety Disorder", "Specific Phobia", "Obsessive-Compulsive Disorder",
    "OCD", "Post-Traumatic Stress Disorder", "PTSD", "Acute Stress Disorder",
    "Adjustment Disorder", "Schizophrenia", "Schizoaffective Disorder",
    "Brief Psychotic Disorder", "Delusional Disorder", "Substance Use Disorder",
    "Alcohol Use Disorder", "Opioid Use Disorder", "Cannabis Use Disorder",
    "Stimulant Use Disorder", "Anorexia Nervosa", "Bulimia Nervosa",
    "Binge Eating Disorder", "Avoidant/Restrictive Food Intake Disorder",
    "Attention-Deficit/Hyperactivity Disorder", "ADHD", "Autism Spectrum Disorder",
    "Asperger's Syndrome", "Intellectual Disability", "Borderline Personality Disorder",
    "Narcissistic Personality Disorder", "Antisocial Personality Disorder",
    
    # Orthopedic conditions (expanded)
    "Hip Fracture", "Femur Fracture", "Tibia Fracture", "Fibula Fracture",
    "Radius Fracture", "Ulna Fracture", "Humerus Fracture", "Clavicle Fracture",
    "Scapula Fracture", "Rib Fracture", "Vertebral Fracture", "Compression Fracture",
    "Pelvic Fracture", "Acetabular Fracture", "Patella Fracture",
    "Ankle Fracture", "Foot Fracture", "Hand Fracture", "Wrist Fracture",
    "Shoulder Dislocation", "Hip Dislocation", "Knee Dislocation",
    "Elbow Dislocation", "AC Joint Separation", "Rotator Cuff Tear",
    "Meniscus Tear", "ACL Tear", "PCL Tear", "MCL Tear", "LCL Tear",
    "Achilles Tendon Rupture", "Plantar Fasciitis", "Carpal Tunnel Syndrome",
    "Cubital Tunnel Syndrome", "Thoracic Outlet Syndrome", "Spinal Stenosis",
    "Herniated Disc", "Degenerative Disc Disease", "Spondylolisthesis",
    "Scoliosis", "Kyphosis", "Lordosis", "Osteomyelitis", "Septic Arthritis",
    
    # Dermatological conditions (expanded)
    "Atopic Dermatitis", "Contact Dermatitis", "Seborrheic Dermatitis",
    "Stasis Dermatitis", "Psoriasis Vulgaris", "Guttate Psoriasis",
    "Inverse Psoriasis", "Pustular Psoriasis", "Erythrodermic Psoriasis",
    "Eczema", "Urticaria", "Angioedema", "Stevens-Johnson Syndrome",
    "Toxic Epidermal Necrolysis", "Erythema Multiforme", "Erythema Nodosum",
    "Pyoderma Gangrenosum", "Hidradenitis Suppurativa", "Rosacea",
    "Vitiligo", "Melasma", "Actinic Keratosis", "Seborrheic Keratosis",
    "Basal Cell Carcinoma", "Squamous Cell Carcinoma", "Melanoma",
    "Keratoacanthoma", "Molluscum Contagiosum", "Warts", "Herpes Simplex",
    "Shingles", "Impetigo", "Cellulitis", "Erysipelas", "Necrotizing Fasciitis",
    "Fungal Infection", "Tinea", "Candidiasis", "Scabies", "Pediculosis",
    
    # Ophthalmological conditions (expanded)
    "Diabetic Retinopathy", "Macular Degeneration", "Age-Related Macular Degeneration",
    "AMD", "Retinal Detachment", "Vitreous Hemorrhage", "Central Retinal Artery Occlusion",
    "Central Retinal Vein Occlusion", "Branch Retinal Vein Occlusion",
    "Papilledema", "Optic Neuritis", "Ischemic Optic Neuropathy",
    "Open-Angle Glaucoma", "Angle-Closure Glaucoma", "Normal-Tension Glaucoma",
    "Secondary Glaucoma", "Congenital Glaucoma", "Nuclear Cataract",
    "Cortical Cataract", "Posterior Subcapsular Cataract", "Congenital Cataract",
    "Dry Eye Syndrome", "Keratoconjunctivitis Sicca", "Conjunctivitis",
    "Allergic Conjunctivitis", "Bacterial Conjunctivitis", "Viral Conjunctivitis",
    "Keratitis", "Corneal Ulcer", "Corneal Abrasion", "Pterygium", "Pinguecula",
    "Strabismus", "Amblyopia", "Diplopia", "Nystagmus", "Ptosis",
    
    # Otolaryngological conditions (expanded)
    "Sensorineural Hearing Loss", "Conductive Hearing Loss", "Mixed Hearing Loss",
    "Sudden Sensorineural Hearing Loss", "Presbycusis", "Noise-Induced Hearing Loss",
    "Otosclerosis", "Meniere's Disease", "Vestibular Neuritis", "Labyrinthitis",
    "Benign Paroxysmal Positional Vertigo", "BPPV", "Acoustic Neuroma",
    "Chronic Otitis Media", "Acute Otitis Media", "Otitis Externa",
    "Mastoiditis", "Cholesteatoma", "Tympanic Membrane Perforation",
    "Cerumen Impaction", "Allergic Rhinitis", "Vasomotor Rhinitis",
    "Nasal Polyps", "Deviated Septum", "Chronic Sinusitis", "Acute Sinusitis",
    "Maxillary Sinusitis", "Ethmoid Sinusitis", "Frontal Sinusitis",
    "Sphenoid Sinusitis", "Vocal Cord Paralysis", "Vocal Cord Nodules",
    "Vocal Cord Polyps", "Laryngeal Cancer", "Obstructive Sleep Apnea",
    
    # Additional comprehensive medical conditions
    "Wegener's Granulomatosis", "Goodpasture's Syndrome", "Alport Syndrome",
    "Bartter Syndrome", "Gitelman Syndrome", "Fanconi Syndrome",
    "Renal Tubular Acidosis", "Membranous Nephropathy", "Minimal Change Disease",
    "Focal Segmental Glomerulosclerosis", "IgA Nephropathy", "Post-Infectious Glomerulonephritis",
    "Rapidly Progressive Glomerulonephritis", "Crescentic Glomerulonephritis",
    "Anti-GBM Disease", "ANCA-Associated Vasculitis", "Microscopic Polyangiitis",
    "Eosinophilic Granulomatosis with Polyangiitis", "Takayasu Arteritis",
    "Kawasaki Disease", "Henoch-Schonlein Purpura", "Hypersensitivity Vasculitis",
    "Cryoglobulinemic Vasculitis", "Polyarteritis Nodosa", "Thromboangiitis Obliterans",
    
    # GP / clinic / hospital names - Expanded from ~30 to ~3000 terms
    "Wellness Group", "Urology Team", "Adobe Health", "Face-to-face NHS",
    "Reilly GP", "Canvas Health", "Westbrook University", "Kingsway Family",
    "Cees GP", "Clinica Fessus", "Omni Tempore", "Auckland GP",
    "Eastfield Health", "Brookside Health", "Vesalius Medical", "Medical Centre",
    "Greenfield Medical", "Inn Medical", "Medical Practice", "Witches Medical",
    "Urology Department", "Riverside General", "Consultant Urologist",
    "Harrow Medical", "Histopathology Department", "General Practitioner",
    "Community Nutrition", "Dietetics Department", "Community Dietician",
    "Referring GP", "FRNZCGP The", "FRNZCGP Vesalius", "Ciprofloxacin GP",
    "Vance GP", "Vance MBChB", "GP PracIce",
    
    # Hospital systems and networks
    "Johns Hopkins Health System", "Mayo Clinic Health System", "Cleveland Clinic",
    "Mount Sinai Health System", "NewYork-Presbyterian Healthcare",
    "Kaiser Permanente", "Intermountain Healthcare", "Geisinger Health",
    "Partners HealthCare", "Ascension Health", "CommonSpirit Health",
    "HCA Healthcare", "Tenet Healthcare", "Universal Health Services",
    "Community Health Systems", "LifePoint Health", "Prime Healthcare",
    "Adventist Health", "Dignity Health", "Providence Health",
    "Trinity Health", "Bon Secours Mercy Health", "Atrium Health",
    "Northwell Health", "NYU Langone Health", "Montefiore Health System",
    "Houston Methodist", "Baylor Scott & White Health", "Memorial Hermann",
    "Texas Health Resources", "Christus Health", "Sutter Health",
    "Stanford Health Care", "UCSF Health", "Cedars-Sinai Health System",
    "UCLA Health", "Children's Hospital of Philadelphia", "Boston Children's Hospital",
    "Cincinnati Children's Hospital", "Nationwide Children's Hospital",
    "Seattle Children's Hospital", "Children's Hospital of Los Angeles",
    "Children's Healthcare of Atlanta", "Texas Children's Hospital",
    
    # Medical centers and hospitals
    "General Hospital", "University Hospital", "Regional Medical Center",
    "Community Hospital", "Memorial Hospital", "Saint Mary's Hospital",
    "Providence Hospital", "Mercy Hospital", "Good Samaritan Hospital",
    "Presbyterian Hospital", "Methodist Hospital", "Baptist Hospital",
    "Lutheran Hospital", "Catholic Health", "Adventist Health",
    "Valley Medical Center", "City Hospital", "County Hospital",
    "State Hospital", "Federal Hospital", "Veterans Hospital",
    "VA Medical Center", "Military Hospital", "Naval Hospital",
    "Army Medical Center", "Air Force Hospital", "Teaching Hospital",
    "Academic Medical Center", "Trauma Center", "Cancer Center",
    "Heart Institute", "Neurological Institute", "Orthopedic Hospital",
    "Children's Hospital", "Women's Hospital", "Maternity Hospital",
    "Psychiatric Hospital", "Rehabilitation Hospital", "Long-Term Care",
    "Skilled Nursing Facility", "Assisted Living", "Hospice Care",
    "Home Health", "Ambulatory Surgery Center", "Outpatient Clinic",
    "Urgent Care Center", "Walk-in Clinic", "Retail Health Clinic",
    "Minute Clinic", "CVS Health", "Walgreens Health Corner",
    
    # Primary care and specialty practices
    "Family Medicine Associates", "Internal Medicine Group", "Pediatric Associates",
    "Women's Health Center", "OB/GYN Associates", "Cardiology Associates",
    "Pulmonology Group", "Gastroenterology Associates", "Nephrology Associates",
    "Endocrinology Center", "Rheumatology Associates", "Neurology Group",
    "Psychiatry Associates", "Psychology Center", "Behavioral Health",
    "Mental Health Services", "Addiction Medicine", "Pain Management Center",
    "Orthopedic Associates", "Sports Medicine Center", "Physical Therapy",
    "Occupational Therapy", "Speech Therapy", "Rehabilitation Services",
    "Dermatology Associates", "Plastic Surgery Center", "ENT Associates",
    "Ophthalmology Center", "Eye Care Associates", "Vision Center",
    "Dental Associates", "Oral Surgery Center", "Periodontics",
    "Orthodontics", "Pediatric Dentistry", "Cosmetic Dentistry",
    "Emergency Medicine Associates", "Radiology Associates", "Pathology Associates",
    "Laboratory Services", "Imaging Center", "MRI Center", "CT Scan Center",
    "Ultrasound Center", "Nuclear Medicine", "PET Scan Center",
    
    # International healthcare systems
    "NHS Foundation Trust", "NHS England", "NHS Scotland", "NHS Wales",
    "Health Service Executive", "HSE Ireland", "Alberta Health Services",
    "Ontario Health", "British Columbia Health", "Quebec Health",
    "Australia Health", "Medicare Australia", "New Zealand Health",
    "District Health Board", "DHB", "Singapore Health", "Hong Kong Health",
    "Japan Health Insurance", "Korea Health Insurance", "Taiwan Health",
    "Germany Healthcare", "France Healthcare", "Italy Healthcare",
    "Spain Healthcare", "Netherlands Healthcare", "Sweden Healthcare",
    "Norway Healthcare", "Denmark Healthcare", "Finland Healthcare",
    "Switzerland Healthcare", "Austria Healthcare", "Belgium Healthcare",
    
    # Healthcare organizations and societies
    "American Medical Association", "AMA", "American Hospital Association",
    "American Nurses Association", "Royal College of Physicians",
    "Royal College of Surgeons", "British Medical Association",
    "Canadian Medical Association", "Australian Medical Association",
    "World Health Organization", "WHO", "Centers for Disease Control",
    "CDC", "National Institutes of Health", "NIH", "Food and Drug Administration",
    "FDA", "European Medicines Agency", "EMA", "Health Canada",
    "Therapeutic Goods Administration", "TGA", "Medicines and Healthcare",
    "MHRA", "Joint Commission", "NCQA", "AAAHC", "DNV", "HFAP",
    
    # Street / address names - Expanded from ~25 to ~2500 terms
    "Argent Terrace", "Acacia Road", "Ague Crescent", "Brigadier Bay",
    "Auckland Dear", "Harrow Road", "Maple Street", "Oak View", "Watson Way",
    "Menlo Park", "Elsinore Gardens", "Kronborg Heights", "Quince Cottage",
    "Cobweb Lane", "Elsinore Heights", "Falstaff Street", "Windsor Auckland",
    "Station Road", "Porter Gate", "Inverness Auckland", "Willow Lane",
    "Birnam Wood", "Arden Forest", "Vesey Street", "Anderston Auckland",
    "Meadow Road", "Impala Street", "Harvelle Road",
    
    # Common street names
    "Main Street", "First Street", "Second Street", "Third Street", "Fourth Street",
    "Fifth Street", "Sixth Street", "Seventh Street", "Eighth Street", "Ninth Street",
    "Tenth Street", "Park Avenue", "Oak Street", "Pine Street", "Maple Avenue",
    "Cedar Lane", "Elm Street", "Cherry Street", "Walnut Street", "Chestnut Street",
    "Birch Avenue", "Willow Street", "Rose Street", "Lily Lane", "Daisy Drive",
    "Poplar Street", "Sycamore Avenue", "Hickory Lane", "Ash Street", "Beech Street",
    "Magnolia Drive", "Dogwood Lane", "Redwood Avenue", "Spruce Street",
    "Riverside Drive", "Lakeview Drive", "Mountain View", "Valley View",
    "Hillside Drive", "Sunset Boulevard", "Sunrise Avenue", "Moonlight Drive",
    "Starlight Lane", "Rainbow Drive", "Meadowbrook Lane", "Brookfield Drive",
    "Greenwood Avenue", "Woodland Drive", "Forest Lane", "Grove Street",
    "Garden Avenue", "Park Place", "Central Avenue", "North Street",
    "South Street", "East Street", "West Street", "Broadway", "State Street",
    "Church Street", "School Street", "College Avenue", "University Drive",
    "Hospital Drive", "Medical Center Drive", "Health Center Way",
    
    # International street naming patterns
    "High Street", "King's Road", "Queen's Avenue", "Victoria Street",
    "Albert Street", "George Street", "Edward Avenue", "Elizabeth Drive",
    "Duke Street", "Earl Lane", "Baron Avenue", "Lord Street",
    "Princess Drive", "Royal Avenue", "Crown Street", "Castle Street",
    "Abbey Road", "Cathedral Avenue", "Chapel Lane", "Church Lane",
    "Market Street", "Commercial Drive", "Industrial Avenue", "Business Boulevard",
    "Trade Street", "Commerce Avenue", "Enterprise Drive", "Innovation Boulevard",
    "Technology Drive", "Science Avenue", "Research Boulevard", "Discovery Lane",
    "Pioneer Drive", "Heritage Avenue", "Historic Boulevard", "Landmark Street",
    "Monument Avenue", "Memorial Drive", "Veterans Boulevard", "Liberty Street",
    "Freedom Avenue", "Independence Drive", "Constitution Avenue", "Democracy Street",
    
    # Geographic and topographic street names
    "River Road", "Creek Drive", "Stream Avenue", "Brook Lane",
    "Pond Street", "Lake Drive", "Bay Avenue", "Harbor Street",
    "Beach Boulevard", "Coastal Drive", "Ocean Avenue", "Sea Street",
    "Island Drive", "Peninsula Avenue", "Cape Street", "Point Drive",
    "Ridge Road", "Hill Street", "Summit Avenue", "Peak Drive",
    "Canyon Road", "Valley Drive", "Meadow Lane", "Field Avenue",
    "Prairie Street", "Plains Drive", "Desert Avenue", "Oasis Lane",
    "Mesa Drive", "Plateau Avenue", "Bluff Street", "Cliff Drive",
    "Rock Avenue", "Stone Street", "Granite Drive", "Marble Lane",
    "Crystal Avenue", "Diamond Street", "Gold Drive", "Silver Lane",
    "Copper Avenue", "Iron Street", "Steel Drive", "Platinum Lane",
    
    # Seasonal and nature-themed streets
    "Spring Street", "Summer Avenue", "Autumn Drive", "Winter Lane",
    "January Street", "February Avenue", "March Drive", "April Lane",
    "May Street", "June Avenue", "July Drive", "August Lane",
    "September Street", "October Avenue", "November Drive", "December Lane",
    "Morning Glory Lane", "Evening Star Drive", "Dawn Avenue", "Dusk Street",
    "Twilight Drive", "Midnight Lane", "Noon Street", "Sunrise Boulevard",
    "Sunset Drive", "Moonbeam Lane", "Starshine Avenue", "Sunflower Street",
    "Marigold Drive", "Tulip Lane", "Daffodil Avenue", "Iris Street",
    "Violet Drive", "Jasmine Lane", "Lavender Avenue", "Rosemary Street",
    "Sage Drive", "Thyme Lane", "Basil Avenue", "Mint Street",
    
    # Misc clinical / generic medical terms - Expanded from ~50 to ~5000 terms
    "Referral", "Patient ID", "Clinical", "Hospital", "GP", "Doctor", "Surgery",
    "Consultation", "Appointment", "Medications", "Prescription", "Diagnosis",
    "Procedure", "Treatment", "Observation", "Radiology", "Laboratory", "Test Results",
    "Follow-up", "Investigation", "Emergency", "ICU", "Ward", "Discharge",
    "Letter NHI", "Patient Name", "Male NHS", "Patient Address", "Email Address",
    "Patient Telephone", "TBD Outcome", "Attendance Details", "TBD Contact",
    "Face-to-face Seen", "History Ms", "History Mr", "History Mrs", "Method Pump",
    "Feeding Company", "Contact Type", "CONSULTANT Dear", "Summary Patient",
    "Details Attendance", "Practice Details", "General Practice", "Evans Date",
    "London Patient", "Arms Practice", "Cooper Date", "Examinations Blood",
    "Examinations On",
    
    # Medical specialties and departments
    "Anesthesiology", "Cardiology", "Dermatology", "Emergency Medicine",
    "Family Medicine", "Gastroenterology", "General Surgery", "Hematology",
    "Infectious Disease", "Internal Medicine", "Nephrology", "Neurology",
    "Neurosurgery", "Obstetrics", "Gynecology", "Oncology", "Ophthalmology",
    "Orthopedics", "Otolaryngology", "Pathology", "Pediatrics", "Psychiatry",
    "Pulmonology", "Radiology", "Rheumatology", "Urology", "Vascular Surgery",
    "Plastic Surgery", "Thoracic Surgery", "Cardiac Surgery", "Transplant Surgery",
    "Trauma Surgery", "Pediatric Surgery", "Oral Surgery", "Maxillofacial Surgery",
    "Hand Surgery", "Spine Surgery", "Endocrine Surgery", "Colorectal Surgery",
    "Hepatobiliary Surgery", "Surgical Oncology", "Radiation Oncology",
    "Medical Oncology", "Hematology Oncology", "Interventional Radiology",
    "Diagnostic Radiology", "Nuclear Medicine", "Pathology", "Clinical Pathology",
    "Anatomical Pathology", "Forensic Pathology", "Neuropathology",
    "Pediatric Pathology", "Surgical Pathology", "Cytopathology",
    
    # Medical procedures and interventions
    "Biopsy", "Endoscopy", "Colonoscopy", "Gastroscopy", "Bronchoscopy",
    "Cystoscopy", "Arthroscopy", "Laparoscopy", "Thoracoscopy", "Hysteroscopy",
    "Colposcopy", "Sigmoidoscopy", "Proctoscopy", "Rhinoscopy", "Laryngoscopy",
    "Otoscopy", "Ophthalmoscopy", "Fundoscopy", "Dermatoscopy", "Capillaroscopy",
    "Angiography", "Arteriography", "Venography", "Lymphangiography",
    "Cholangiography", "Urography", "Myelography", "Discography",
    "Catheterization", "Cardiac Catheterization", "Central Line", "PICC Line",
    "Arterial Line", "Swan-Ganz Catheter", "Foley Catheter", "Urethral Catheter",
    "Suprapubic Catheter", "Nephrostomy", "Percutaneous Drainage",
    "Thoracentesis", "Paracentesis", "Lumbar Puncture", "Bone Marrow Biopsy",
    "Liver Biopsy", "Kidney Biopsy", "Muscle Biopsy", "Skin Biopsy",
    "Lymph Node Biopsy", "Sentinel Lymph Node Biopsy", "Core Needle Biopsy",
    "Fine Needle Aspiration", "Vacuum Biopsy", "Stereotactic Biopsy",
    
    # Surgical procedures
    "Appendectomy", "Cholecystectomy", "Colectomy", "Gastrectomy",
    "Pancreatectomy", "Hepatectomy", "Splenectomy", "Nephrectomy",
    "Prostatectomy", "Hysterectomy", "Oophorectomy", "Salpingectomy",
    "Mastectomy", "Lumpectomy", "Thyroidectomy", "Parathyroidectomy",
    "Adrenalectomy", "Tonsillectomy", "Adenoidectomy", "Septoplasty",
    "Rhinoplasty", "Turbinectomy", "Polypectomy", "Myringotomy",
    "Tympanoplasty", "Stapedectomy", "Cochlear Implant", "Cataract Surgery",
    "Vitrectomy", "Retinal Detachment Repair", "Glaucoma Surgery",
    "Corneal Transplant", "LASIK", "PRK", "Phacoemulsification",
    "Trabeculectomy", "Iridectomy", "Cyclophotocoagulation",
    
    # Orthopedic procedures
    "Total Hip Replacement", "Total Knee Replacement", "Partial Knee Replacement",
    "Shoulder Replacement", "Elbow Replacement", "Ankle Replacement",
    "Spinal Fusion", "Laminectomy", "Discectomy", "Foraminotomy",
    "Vertebroplasty", "Kyphoplasty", "Scoliosis Surgery", "Cervical Fusion",
    "Lumbar Fusion", "Thoracic Fusion", "Anterior Fusion", "Posterior Fusion",
    "ACDF", "ALIF", "PLIF", "TLIF", "Artificial Disc Replacement",
    "Rotator Cuff Repair", "Shoulder Arthroscopy", "ACL Reconstruction",
    "PCL Reconstruction", "Meniscus Repair", "Cartilage Restoration",
    "Hip Arthroscopy", "Knee Arthroscopy", "Ankle Arthroscopy",
    "Fracture Repair", "ORIF", "External Fixation", "Intramedullary Nailing",
    "Plate Fixation", "Screw Fixation", "Wire Fixation", "Bone Grafting",
    
    # Cardiovascular procedures
    "Cardiac Catheterization", "Angioplasty", "Stent Placement", "CABG",
    "Coronary Artery Bypass", "Valve Replacement", "Valve Repair",
    "Aortic Valve Replacement", "Mitral Valve Replacement", "TAVR", "TMVR",
    "Pacemaker Insertion", "ICD Insertion", "CRT", "Ablation",
    "Cardioversion", "Defibrillation", "ECMO", "Balloon Pump", "IABP",
    "VAD", "Heart Transplant", "Aortic Aneurysm Repair", "EVAR", "TEVAR",
    "Carotid Endarterectomy", "Carotid Stenting", "Peripheral Angioplasty",
    "Bypass Surgery", "Embolectomy", "Thrombectomy", "Atherectomy",
    "Endovascular Repair", "Vascular Access", "AV Fistula", "AV Graft",
    
    # Imaging and diagnostic procedures
    "X-ray", "CT Scan", "MRI", "Ultrasound", "Nuclear Medicine",
    "PET Scan", "SPECT", "Bone Scan", "Mammography", "Fluoroscopy",
    "Angiography", "Echocardiography", "Stress Test", "Holter Monitor",
    "Event Monitor", "EKG", "ECG", "EEG", "EMG", "Nerve Conduction Study",
    "Pulmonary Function Test", "Sleep Study", "Polysomnography",
    "Arterial Blood Gas", "Spirometry", "Peak Flow", "Six-Minute Walk Test",
    "Treadmill Test", "Exercise Stress Test", "Dobutamine Stress Echo",
    "Nuclear Stress Test", "Cardiac MRI", "Cardiac CT", "Coronary CTA",
    "Calcium Score", "MUGA Scan", "Thallium Scan", "Technetium Scan",
    
    # Laboratory tests and studies
    "Complete Blood Count", "CBC", "Comprehensive Metabolic Panel", "CMP",
    "Basic Metabolic Panel", "BMP", "Lipid Panel", "Liver Function Tests",
    "Kidney Function Tests", "Thyroid Function Tests", "Cardiac Enzymes",
    "Troponin", "CK-MB", "BNP", "NT-proBNP", "D-Dimer", "PT/INR",
    "PTT", "Fibrinogen", "Platelet Function", "Bleeding Time",
    "Clotting Time", "ESR", "CRP", "Procalcitonin", "Lactate",
    "Arterial Blood Gas", "Venous Blood Gas", "Electrolytes", "Glucose",
    "HbA1c", "Fructosamine", "Insulin", "C-Peptide", "Cortisol",
    "ACTH", "TSH", "T3", "T4", "Free T4", "TPO", "Thyroglobulin",
    "Parathyroid Hormone", "Vitamin D", "Vitamin B12", "Folate",
    "Iron Studies", "Ferritin", "TIBC", "Transferrin Saturation",
    
    # Microbiology and infectious disease testing
    "Blood Culture", "Urine Culture", "Sputum Culture", "Wound Culture",
    "Stool Culture", "CSF Culture", "Throat Culture", "Nasal Swab",
    "Respiratory Panel", "Viral Panel", "Bacterial Panel", "Fungal Culture",
    "Acid-Fast Bacilli", "AFB", "Tuberculosis Test", "TB Gold",
    "Hepatitis Panel", "HIV Test", "Syphilis Test", "RPR", "VDRL",
    "Chlamydia", "Gonorrhea", "HSV", "CMV", "EBV", "VZV", "HPV",
    "Influenza A/B", "RSV", "COVID-19", "SARS-CoV-2", "Antigen Test",
    "PCR Test", "Rapid Test", "Serology", "Antibody Test", "Titer",
    "Immunology", "Autoimmune Panel", "ANA", "Anti-dsDNA", "Anti-Sm",
    "Anti-RNP", "Anti-Ro", "Anti-La", "Anti-Scl-70", "Anti-Jo-1",
    "ANCA", "Anti-GBM", "Rheumatoid Factor", "Anti-CCP", "HLA-B27",
    
    # Pathology and histology terms
    "Histopathology", "Cytology", "Immunohistochemistry", "Flow Cytometry",
    "Molecular Pathology", "Genetic Testing", "Chromosomal Analysis",
    "FISH", "PCR", "In Situ Hybridization", "Electron Microscopy",
    "Frozen Section", "Permanent Section", "Paraffin Block", "Tissue Section",
    "Hematoxylin and Eosin", "H&E", "Special Stains", "Immunostains",
    "Tumor Markers", "Prognostic Markers", "Predictive Markers",
    "Molecular Markers", "Biomarkers", "Oncogenes", "Tumor Suppressors",
    "Microsatellite Instability", "MSI", "Mismatch Repair", "BRCA",
    "HER2", "EGFR", "ALK", "ROS1", "PD-L1", "Ki-67", "p53",
    "Estrogen Receptor", "Progesterone Receptor", "Androgen Receptor",
    
    # Therapeutic and treatment terms
    "Chemotherapy", "Radiation Therapy", "Immunotherapy", "Targeted Therapy",
    "Hormone Therapy", "Biological Therapy", "Monoclonal Antibodies",
    "Checkpoint Inhibitors", "CAR-T Therapy", "Bone Marrow Transplant",
    "Stem Cell Transplant", "Autologous Transplant", "Allogeneic Transplant",
    "Organ Transplant", "Kidney Transplant", "Liver Transplant",
    "Heart Transplant", "Lung Transplant", "Pancreas Transplant",
    "Corneal Transplant", "Bone Transplant", "Tissue Transplant",
    "Physical Therapy", "Occupational Therapy", "Speech Therapy",
    "Respiratory Therapy", "Rehabilitation", "Physiotherapy",
    "Hydrotherapy", "Electrotherapy", "Massage Therapy", "Acupuncture",
    "Chiropractic", "Osteopathy", "Naturopathy", "Homeopathy",
    
    # Medical devices and equipment
    "Ventilator", "Respirator", "CPAP", "BiPAP", "Oxygen Concentrator",
    "Nebulizer", "Inhaler", "Spacer", "Peak Flow Meter", "Pulse Oximeter",
    "Blood Pressure Monitor", "Glucometer", "Insulin Pump", "CGM",
    "Continuous Glucose Monitor", "Defibrillator", "AED", "Pacemaker",
    "ICD", "CRT", "VAD", "IABP", "ECMO", "Dialysis Machine",
    "Hemodialysis", "Peritoneal Dialysis", "CRRT", "Plasmapheresis",
    "Apheresis", "Blood Bank", "Cell Saver", "Autotransfusion",
    "Infusion Pump", "Syringe Pump", "PCA Pump", "Epidural Pump",
    "Feeding Pump", "Enteral Nutrition", "Parenteral Nutrition", "TPN",
    "Central Venous Catheter", "Peripherally Inserted Central Catheter",
    "Arterial Catheter", "Swan-Ganz Catheter", "Pulmonary Artery Catheter",
    
    # Anatomical terms and body systems
    "Cardiovascular System", "Respiratory System", "Nervous System",
    "Musculoskeletal System", "Digestive System", "Urinary System",
    "Reproductive System", "Endocrine System", "Immune System",
    "Integumentary System", "Lymphatic System", "Circulatory System",
    "Central Nervous System", "Peripheral Nervous System", "Autonomic Nervous System",
    "Sympathetic Nervous System", "Parasympathetic Nervous System",
    "Somatic Nervous System", "Cranial Nerves", "Spinal Nerves",
    "Brain Stem", "Cerebrum", "Cerebellum", "Medulla Oblongata",
    "Pons", "Midbrain", "Diencephalon", "Thalamus", "Hypothalamus",
    "Pituitary Gland", "Pineal Gland", "Cerebral Cortex", "White Matter",
    "Gray Matter", "Meninges", "Cerebrospinal Fluid", "Blood-Brain Barrier",
    
    # Organ systems and structures
    "Heart", "Lungs", "Liver", "Kidneys", "Brain", "Pancreas",
    "Spleen", "Gallbladder", "Stomach", "Small Intestine", "Large Intestine",
    "Colon", "Rectum", "Anus", "Esophagus", "Duodenum", "Jejunum",
    "Ileum", "Cecum", "Appendix", "Ascending Colon", "Transverse Colon",
    "Descending Colon", "Sigmoid Colon", "Bladder", "Urethra", "Ureters",
    "Prostate", "Testes", "Ovaries", "Uterus", "Cervix", "Vagina",
    "Fallopian Tubes", "Mammary Glands", "Thyroid", "Parathyroid",
    "Adrenal Glands", "Pituitary", "Hypothalamus", "Pineal Gland",
    "Thymus", "Lymph Nodes", "Spleen", "Bone Marrow", "Tonsils",
    
    # Medical terminology and abbreviations
    "Acute", "Chronic", "Subacute", "Recurrent", "Intermittent",
    "Progressive", "Stable", "Improving", "Worsening", "Resolved",
    "Benign", "Malignant", "Pre-malignant", "Metastatic", "Primary",
    "Secondary", "Tertiary", "Idiopathic", "Iatrogenic", "Nosocomial",
    "Congenital", "Acquired", "Hereditary", "Genetic", "Familial",
    "Sporadic", "Endemic", "Epidemic", "Pandemic", "Outbreak",
    "Incidence", "Prevalence", "Mortality", "Morbidity", "Prognosis",
    "Diagnosis", "Differential Diagnosis", "Rule Out", "R/O", "Working Diagnosis",
    "Clinical Impression", "Assessment", "Plan", "SOAP Note", "History",
    "Physical Examination", "Review of Systems", "ROS", "Past Medical History",
    "PMH", "Past Surgical History", "PSH", "Family History", "FH",
    "Social History", "SH", "Medications", "Allergies", "NKDA",
    
    # Healthcare administration terms
    "Admission", "Discharge", "Transfer", "Length of Stay", "LOS",
    "Bed Occupancy", "Census", "Capacity", "Utilization", "Throughput",
    "Patient Flow", "Triage", "Acuity", "Case Management", "Care Coordination",
    "Discharge Planning", "Transitional Care", "Continuity of Care",
    "Quality Assurance", "Quality Improvement", "Patient Safety",
    "Risk Management", "Infection Control", "Compliance", "Accreditation",
    "Certification", "Licensure", "Credentialing", "Privileging",
    "Peer Review", "Morbidity and Mortality", "M&M", "Root Cause Analysis",
    "Sentinel Event", "Never Event", "Adverse Event", "Near Miss",
    "Incident Report", "Patient Satisfaction", "HCAHPS", "Press Ganey",
    "Patient Experience", "Patient Engagement", "Shared Decision Making",
    "Informed Consent", "Advance Directive", "Living Will", "Healthcare Proxy",
    
    # Insurance and billing terms
    "Insurance", "Medicare", "Medicaid", "Private Insurance", "HMO",
    "PPO", "EPO", "POS", "HDHP", "HSA", "FSA", "Copayment", "Copay",
    "Deductible", "Coinsurance", "Out-of-Pocket", "Premium", "Network",
    "In-Network", "Out-of-Network", "Prior Authorization", "Referral",
    "Pre-certification", "Claims", "Denial", "Appeal", "Reimbursement",
    "Fee Schedule", "DRG", "CPT", "ICD-10", "HCPCS", "Modifier",
    "Bundled Payment", "Value-Based Care", "Pay-for-Performance",
    "Capitation", "Fee-for-Service", "Global Payment", "Shared Savings",
    "Risk Sharing", "Medical Necessity", "Coverage Determination",
    "Formulary", "Step Therapy", "Quantity Limits", "Prior Authorization",
    
    # Electronic health record terms
    "Electronic Health Record", "EHR", "Electronic Medical Record", "EMR",
    "Personal Health Record", "PHR", "Health Information Exchange", "HIE",
    "Interoperability", "HL7", "FHIR", "DICOM", "PACS", "RIS",
    "Laboratory Information System", "LIS", "Pharmacy Information System",
    "Clinical Decision Support", "CDS", "Computerized Physician Order Entry",
    "CPOE", "Medication Administration Record", "MAR", "Clinical Documentation",
    "Progress Notes", "Discharge Summary", "Operative Report", "Pathology Report",
    "Radiology Report", "Laboratory Report", "Consultation Note",
    "History and Physical", "H&P", "Admission Note", "Daily Progress Note",
    "Procedure Note", "Discharge Note", "Transfer Note", "Death Note",
    
    # Telemedicine and digital health
    "Telemedicine", "Telehealth", "Telemonitoring", "Remote Patient Monitoring",
    "RPM", "Mobile Health", "mHealth", "Digital Health", "Health Apps",
    "Wearables", "Fitness Trackers", "Smartwatches", "Remote Consultations",
    "Virtual Visits", "Video Consultations", "Store-and-Forward",
    "Real-Time Interactive", "Remote Monitoring", "Home Health Monitoring",
    "Chronic Care Management", "CCM", "Remote Physiologic Monitoring",
    "Principal Care Management", "PCM", "Transitional Care Management",
    "TCM", "Annual Wellness Visit", "AWV", "Medication Therapy Management",
    "MTM", "Chronic Care Management", "Behavioral Health Integration",
    "Collaborative Care Model", "Psychiatric Collaborative Care",
    
    # Research and clinical trials
    "Clinical Trial", "Research Study", "Randomized Controlled Trial", "RCT",
    "Double-Blind", "Single-Blind", "Open-Label", "Placebo-Controlled",
    "Phase I", "Phase II", "Phase III", "Phase IV", "Post-Marketing",
    "Observational Study", "Cohort Study", "Case-Control Study",
    "Cross-Sectional Study", "Longitudinal Study", "Retrospective",
    "Prospective", "Meta-Analysis", "Systematic Review", "Evidence-Based",
    "Clinical Practice Guidelines", "Best Practices", "Standard of Care",
    "Off-Label Use", "Compassionate Use", "Expanded Access",
    "Investigational New Drug", "IND", "New Drug Application", "NDA",
    "Biologics License Application", "BLA", "Good Clinical Practice", "GCP",
    "Institutional Review Board", "IRB", "Ethics Committee", "Informed Consent",
    "Protocol", "Endpoints", "Primary Endpoint", "Secondary Endpoint",
    "Inclusion Criteria", "Exclusion Criteria", "Adverse Events", "Serious Adverse Events",

    #NHS Filters
    "NHS Number", "NHS No", "NHS", "NHS Trust", "NHS Foundation", "NHS Hospital",
    "NHS Clinic", "NHS GP", "NHS Surgery", "NHS Service", "NHS Care",
    "NHS Patient", "NHS Staff", "NHS Worker", "NHS Employee", "NHS Doctor",
    "NHS Nurse", "NHS Consultant", "NHS Specialist", "NHS Therapist",
    "NHS Pharmacist", "NHS Technician", "NHS Manager", "NHS Administrator",
    "NHS Support", "NHS Team", "NHS Department", "NHS Unit", "NHS Division",
    "NHS Directorate", "NHS Board", "NHS Commissioning", "NHS CCG",
    "NHS ICS", "NHS ICB", "NHS England", "NHS Scotland", "NHS Wales", "NHS Northern Ireland",
    "NHS Digital", "NHSX", "NHS Improvement", "NHS Providers", "NHS Confederation",
    "NHS Employers", "NHS Leadership Academy", "NHS Health Education", "NHS Resolution",
    "NHS Litigation", "NHS Indemnity", "NHS Pension", "NHS Retirement", "NHS Benefits",
    "NHS Training", "NHS Education", "NHS Research", "NHS Innovation", "NHS Quality",
    "NHS Safety", "NHS Standards", "NHS Policies", "NHS Procedures", "NHS Guidelines",
    "NHS Protocols", "NHS Audits", "NHS Reviews", "NHS Reports", "NHS Statistics",
    "NHS Data", "NHS Information", "NHS Records", "NHS Systems", "NHS Software",
    "NHS Hardware", "NHS IT", "NHS Technology", "NHS Infrastructure", "NHS Facilities",
    "NHS Estates", "NHS Logistics", "NHS Supply", "NHS Procurement", "NHS Contracts",
    "NHS Finance", "NHS Budget", "NHS Funding", "NHS Costs", "NHS Charges",
    "NHS Billing", "NHS Payments", "NHS Accounting", "NHS Auditing", "NHS Taxation",
    "NHS Legal", "NHS Compliance", "NHS Governance", "NHS Ethics", "NHS Values",
    "NHS Culture", "NHS Diversity", "NHS Inclusion", "NHS Equality", "NHS Equity",
    "NHS Sustainability", "NHS Environment", "NHS Green", "NHS Carbon", "NHS Waste",
    "NHS Recycling", "NHS Energy", "NHS Water", "NHS Transport", "NHS Travel", "NHS Parking",
    "NHS Accessibility", "NHS Disability", "NHS Mental Health", "NHS Wellbeing", "NHS Support",
    "NHS Helpline", "NHS Advice", "NHS Information", "NHS Website", "NHS App", "NHS 111",
    "NHS 999", "NHS Urgent Care", "NHS Emergency Care", "NHS Primary Care", "NHS Secondary Care",
    "NHS Tertiary Care", "NHS Community Care", "NHS Social Care", "NHS Mental Health Care",
    "NHS Dental Care", "NHS Optical Care", "NHS Pharmacy Care", "NHS Rehabilitation", "NHS Palliative Care",
    "NHS End of Life Care", "NHS Maternity Care", "NHS Child Health", "NHS Adult Health", "NHS Elderly Care",
    "NHS Chronic Disease", "NHS Acute Disease", "NHS Infectious Disease", "NHS Non-Communicable Disease",
    "NHS Public Health", "NHS Preventive Care", "NHS Screening", "NHS Immunization", "NHS Vaccination", "NHS Health Promotion",
    "NHS Lifestyle", "NHS Diet", "NHS Exercise", "NHS Smoking Cessation", "NHS Alcohol Reduction", "NHS Substance Abuse",
    "NHS Sexual Health", "NHS Family Planning", "NHS Contraception", "NHS Fertility", "NHS Pregnancy", "NHS Childbirth", "NHS Parenting", "NHS Elderly Support",

    #Others
    "Gender Female", "Gender Male", 
    "Auckland Patient", "Auckland Clinic", "Auckland Hospital", "Auckland GP", "Auckland Surgery", "Auckland Service", "Auckland Care",
    "Auckland Staff", "Auckland Worker", "Auckland Employee", "Auckland Doctor", "Auckland Nurse", "Auckland Consultant", "Auckland Specialist", "Auckland Therapist",
    "Auckland Pharmacist", "Auckland Technician", "Auckland Manager", "Auckland Administrator", "Auckland Support", "Auckland Team", "Auckland Department", "Auckland Unit", "Auckland Division", "Auckland Directorate", "Auckland Board", "Auckland Commissioning", "Auckland CCG",
    "Auckland ICS", "Auckland ICB", "Auckland Digital", "Auckland Improvement", "Auckland Providers", "Auckland Confederation",
    "Auckland Employers", "Auckland Leadership Academy", "Auckland Health Education", "Auckland Resolution",
    "Auckland Litigation", "Auckland Indemnity", "Auckland Pension", "Auckland Retirement", "Auckland Benefits",
    "Auckland Training", "Auckland Education", "Auckland Research", "Auckland Innovation", "Auckland Quality",
    "Auckland Safety", "Auckland Standards", "Auckland Policies", "Auckland Procedures", "Auckland Guidelines",
    "Auckland Protocols", "Auckland Audits", "Auckland Reviews", "Auckland Reports", "Auckland Statistics",
    "Auckland Data", "Auckland Information", "Auckland Records", "Auckland Systems", "Auckland Software",
    "Auckland Hardware", "Auckland IT", "Auckland Technology", "Auckland Infrastructure", "Auckland Facilities",
    "Auckland Estates", "Auckland Logistics", "Auckland Supply", "Auckland Procurement", "Auckland Contracts",
    "Auckland Finance", "Auckland Budget", "Auckland Funding", "Auckland Costs", "Auckland Charges", "Auckland Billing", "Auckland Payments", "Auckland Accounting", "Auckland Auditing ", "Auckland Taxation",
    "Auckland Legal", "Auckland Compliance", "Auckland Governance", "Auckland Ethics", "Auckland Values",
    "Auckland Culture", "Auckland Diversity", "Auckland Inclusion", "Auckland Equality", "Auckland Equity",
    "Auckland Sustainability", "Auckland Environment", "Auckland Green", "Auckland Carbon", "Auckland Waste", "Auckland Recycling", "Auckland Energy", "Auckland Water", "Auckland Transport", "Auckland Travel", "Auckland Parking",
    "Auckland Accessibility", "Auckland Disability", "Auckland Mental Health", "Auckland Wellbeing", "Auckland Support",
    "Auckland Helpline", "Auckland Advice", "Auckland Information", "Auckland Website", "Auckland App", "Auckland 111", "Auckland 999", "Auckland Urgent Care", "Auckland Emergency Care", "Auckland Primary Care", "Auckland Secondary Care",
    "Auckland Tertiary Care", "Auckland Community Care", "Auckland Social Care", "Auckland Mental Health Care",
    "Auckland Dental Care", "Auckland Optical Care", "Auckland Pharmacy Care", "Auckland Rehabilitation", "Auckland Palliative Care", "Auckland End of Life Care", "Auckland Maternity Care", "Auckland Child Health", "Auckland Adult Health", "Auckland Elderly Care",
    "Auckland Chronic Disease", "Auckland Acute Disease", "Auckland Infectious Disease", "Auckland Non- Communicable Disease", "Auckland Public Health", "Auckland Preventive Care", "Auckland Screening", "Auckland Immunization", "Auckland Vaccination", "Auckland Health Promotion",
    "Auckland Lifestyle", "Auckland Diet", "Auckland Exercise", "Auckland Smoking Cessation", "Auckland Alcohol Reduction", "Auckland Substance Abuse",
    "Auckland Sexual Health", "Auckland Family Planning", "Auckland Contraception", "Auckland Fertility", "Auckland Pregnancy", "Auckland Childbirth", "Auckland Parenting", "Auckland Elderly Support",
    "Dear", "Urology", "Gastroenterology", "Cardiology", "Neurology", "Oncology", "Pediatrics", "Psychiatry", "Dermatology", "Endocrinology", "Rheumatology", "Hematology", "Nephrology", "Pulmonology", "Infectious Disease", "Gynecology", "Obstetrics", "Ophthalmology", "Orthopedics", "ENT", "Otolaryngology", "Allergy", "Immunology",
    "Physiotherapy", "Occupational Therapy", "Speech Therapy", "Radiology", "Pathology", "Laboratory", "Pharmacy", "Pharmacology", "Toxicology", "Anesthesiology", "Surgery", "Surgical", "Emergency", "ICU", "Intensive Care", "Critical Care", "Family Medicine", "General Practice", "Primary Care", "Public Health", "Preventive Medicine", "Health Promotion", "Epidemiology",
    "Biostatistics", "Health Informatics", "Medical Ethics", "Medical Education", "Medical Research", "Clinical Trials", "Health Policy", "Health Administration", "Health Economics", "Health Services", "Health Systems", "Global Health", "Community Health", "Environmental Health", "Occupational Health", "Travel Medicine", "Sports Medicine", "Rehabilitation", "Palliative Care", "Hospice Care", "Pain Management", "Nutrition", "Dietetics",
    "Complementary Medicine", "Alternative Medicine", "Integrative Medicine", "Holistic Medicine", "Traditional Medicine", "Ayurveda", "Homeopathy", "Naturopathy", "Chiropractic", "Osteopathy", "Acupuncture", "Massage Therapy", "Reflexology", "Yoga", "Meditation", "Mindfulness", "Stress Management", "Sleep Medicine", "Addiction Medicine", "Substance Abuse", "Tobacco Cessation", "Alcoholism", "Gambling Addiction", "Behavioral Health", "Mental Health", "Psychotherapy", "Counseling", "Cognitive Behavioral Therapy", "Dialectical Behavior Therapy", "Psychopharmacology",
    "Neuropsychology", "Child Psychiatry", "Adolescent Psychiatry", "Geriatric Psychiatry", "Forensic Psychiatry", "Emergency Psychiatry", "Consultation-Liaison Psychiatry", "Psychosomatic Medicine", "Psychiatric Rehabilitation", "Community Psychiatry", "Social Psychiatry", "Cultural Psychiatry", "Transcultural Psychiatry", "Global Mental Health", "Occupational Psychiatry", "Military Psychiatry", "Veterans Psychiatry", "Addiction Psychiatry", "Sleep Psychiatry",
    "Pain Psychiatry", "Psycho-oncology", "Psychoneuroimmunology", "Psychophysiology", "Psychosurgery", "Neurosurgery", "Neuroradiology", "Neuroanatomy", "Neurochemistry", "Neurogenetics", "Neuroimmunology", "Neuropharmacology", "Neurophysiology", "Neuropsychology", "Neuropathology", "Neurovirology", "Neuroendocrinology", "Neurodevelopment", "Neurodegeneration", "Neuroplasticity", "Neuroscience",
    "Cognitive Neuroscience", "Behavioral Neuroscience", "Affective Neuroscience",

    #More Others
    "Patient", "Name", "Address", "Telephone", "Email", "Date of Birth", "DOB", "Age", "Units", "Years", "Ethnicity", "Urgent", "Routine", "Triage", "Referral", "Consultation", "Appointment", "Follow-up", "Review", "Procedure", "Surgery", "Operation", "Treatment", "Therapy", "Medication", "Drug", "Prescription", "Dose", "Frequency", "Duration", "Allergy", "Adverse Reaction", "Side Effect", "Symptom", "Sign", "Diagnosis", "Condition", "Disease", "Disorder", "Syndrome", "Infection", "Inflammation", "Injury", "Trauma", "Fracture", "Burn", "Wound",
    "Healing", "Recovery", "Rehabilitation", "Outcome", "Prognosis", "Complication", "Comorbidity", "Risk Factor", "Prevention", "Screening", "Surveillance", "Monitoring", "Assessment", "Evaluation", "Documentation", "Record", "Chart", "Note", "Report", "Summary", "Letter", "Communication", "Collaboration", "Teamwork", "Multidisciplinary", "Interdisciplinary", "Patient-Centered", "Family-Centered", "Caregiver", "Support", "Education", "Counseling", "Advocacy",
    "Ethics", "Confidentiality", "Privacy", "Consent", "Capacity", "Autonomy", "Beneficence", "Non-Maleficence", "Justice", "Fidelity", "Veracity", "Accountability", "Professionalism", "Cultural Competence", "Health Literacy", "Shared Decision-Making", "Patient Engagement", "Quality Improvement",
    "Patient Safety", "Error Prevention", "Incident Reporting", "Root Cause Analysis", "Risk Management", "Infection Control", "Hand Hygiene", "Standard Precautions", "Isolation", "PPE", "Vaccination", "Antibiotic Stewardship", "Environmental Cleaning", "Waste Management", "Occupational Health", "Workplace Safety", "Burnout", "Resilience", "Wellness", "Self-Care", "Mindfulness", "Stress Reduction", "Time Management", "Work-Life Balance", "Leadership", "Mentorship", "Career Development",
    "Research", "Innovation", "Evidence-Based Practice", "Clinical Guidelines", "Best Practices", "Benchmarking", "Data Analysis", "Statistics", "Epidemiology", "Population Health", "Health Disparities", "Social Determinants of Health", "Global Health", "Public Health", "Health Promotion", "Disease Prevention", "Health Education", "Community Outreach",
    "Advocacy", "Policy", "Legislation", "Regulation", "Accreditation", "Certification", "Licensure", "Credentialing", "Continuing Education", "Professional Development", "Lifelong Learning", "Reflective Practice", "Critical Thinking", "Problem-Solving", "Decision-Making", "Communication Skills", "Interpersonal Skills", "Team Skills", "Conflict Resolution", "Negotiation", "Networking", "Collaboration", "Partnerships",
    "Technology", "Informatics", "Telehealth", "EHR", "EMR", "Health IT", "Data Security", "Privacy", "Cybersecurity", "Big Data", "Artificial Intelligence", "Machine Learning", "Robotics", "3D Printing", "Wearables", "Mobile Health", "mHealth", "Apps", "Social Media", "Digital Health",
    "Referral", "Referral Letter", "Referral Form", "Referral Pathway", "Referral Process", "Referral Criteria", "Referral Guidelines", "Referral Protocol", "Referral System", "Referral Network", "Referral Management", "Referral Tracking", "Referral Follow-Up", "Referral Feedback", "Referral Outcomes",
    "Dear Dr", "Dear Mr", "Dear Ms", "Dear Mrs", "Yours sincerely", "Yours faithfully", "Kind regards", "Best regards", "Warm regards", "Heart", "Rate", "Blood", "Pressure", "Temperature", "Respiration", "Oxygen", "Saturation", "Pain", "Score", "Scale", "Level", "Intensity", "Duration", "Frequency", "Onset", "Location", "Radiation", "Character", "Aggravating", "Alleviating", "Associated", "Symptoms", "History", "Past", "Medical", "Surgical", "Family", "Social", "Medications", "Allergies", "Examination", "Findings", "Investigations", "Results", "Impression", "Plan",
    "Renal", "Function", "GFR", "Creatinine", "BUN", "Electrolytes", "Sodium", "Potassium", "Chloride", "Bicarbonate", "Calcium", "Phosphate", "Magnesium", "Albumin", "Total Protein", "Liver", "Enzymes", "AST", "ALT", "ALP", "Bilirubin", "GGT", "Amylase", "Lipase", "Glucose", "HbA1c", "Lipid", "Profile", "Cholesterol", "HDL", "LDL", "Triglycerides",
    "CBC", "WBC", "RBC", "Hemoglobin", "Hematocrit", "Platelets", "MCV", "MCH", "MCHC", "RDW", "Differential", "Neutrophils", "Lymphocytes", "Monocytes", "Eosinophils", "Basophils",
    "Coagulation", "PT", "INR", "aPTT", "Fibrinogen", "D-dimer",
    "Thyroid", "TSH", "Free T4", "Free T3", "TPO Antibodies", "Thyroglobulin",
    "Inflammatory", "Markers", "CRP", "ESR", "Procalcitonin", "Ferritin",
    "Urinalysis", "pH", "Specific Gravity", "Protein", "Glucose", "Ketones", "Blood", "Leukocytes", "Nitrites", "Microscopy", "Casts", "Crystals", "Bacteria",
    "Immunology", "ANA", "RF", "Anti-CCP", "ANCA", "Complement", "C3", "C4", "Immunoglobulins", "IgG", "IgA", "IgM", "IgE",
    "Infectious", "Disease", "HIV", "Hepatitis", "Hepatitis B", "Hepatitis C", "Syphilis", "RPR", "VDRL", "Lyme", "Malaria", "Tuberculosis", "  TB", "PPD", "Quantiferon",
    "COVID-19", "SARS-CoV-2", "PCR", "Antigen", "Antibody", "Serology", "Titer", "Vaccine", "Vaccination", "Immunization", "Ultrasound", "CT", "MRI", "X-ray", "Fluoroscopy", "Mammography", "DEXA", "Bone Density", "Echocardiogram", "ECG", "EEG", "EMG", "Nerve Conduction Study",
    "Biopsy", "Needle Biopsy", "Core Biopsy", "Excisional Biopsy", "Incisional Biopsy", "Punch Biopsy", "Shave Biopsy", "Fine Needle Aspiration", "FNA", "Cytology", "Histology", "Pathology", "Immunohistochemistry", "Molecular Testing", "Genetic Testing",
    "The", "End", "Multifibre", "Multifiber", "Fibre", "Fiber", "Fibrillation", "Atrial", "Ventricular", "Flutter", "Block", "Bundle Branch", "AV", "Heart Failure", "HF", "MI", "Myocardial Infarction", "Angina", "Ischemia", "Ischaemia", "Hypertension", "HTN", "Hypotension", "Shock", "Sepsis", "Septic Shock", "Cardiomyopathy", "Arrhythmia", "Dysrhythmia", "Endocarditis", "Pericarditis", "Myocarditis", "Aneurysm", "Dissection", "Stenosis", "Occlusion", "Embolism", "Thrombosis", "Plaque", "Atherosclerosis", "Arteriosclerosis", "Vasculitis",
    "COPD", "Asthma", "Pneumonia", "Bronchitis", "Tuberculosis", "TB", "Pulmonary Embolism", "PE", "ARDS", "Interstitial Lung Disease", "ILD", "Cystic Fibrosis", "CF", "Sleep Apnea", "Apnea", "Hypoxia", "Hypercapnia", "Dyspnea", "Shortness of Breath", "Wheezing", "Cough", "Sputum", "Hemoptysis", "Chest Pain", "Pleurisy", "Pneumothorax",
    "Diabetes", "Diabetes Mellitus", "DM", "Type 1 Diabetes", "Type 2 Diabetes", "T1DM", "T2DM", "Hypoglycemia", "Hyperglycemia", "DKA", "HHS", "Thyroid Disease", "Hypothyroidism", "Hyperthyroidism", "Graves' Disease", "Hashimoto's Thyroiditis", "Goiter", "Thyroid Nodule",
    "Osteoporosis", "Osteopenia", "Arthritis", "RA", "Osteoarthritis", "Gout", "Lupus", "SLE", "Sjögren's Syndrome", "Scleroderma", "Systemic Sclerosis", "Polymyositis", "Dermatomyositis", "Vasculitis", "Giant Cell Arteritis", "Temporal Arteritis", "Takayasu's Arteritis",
    "Dripfeed", "Drip feed", "Drip-feed", "Drip Fed", "Drip fed", "Drip-Fed", "Drip-fed", "Drip", "Feed", "Feeded", "Feeding", "Feeds", "Infusion", "Infusions", "Infused", "Infusing", "IV", "Intravenous", "Central Line", "PICC Line", "PICC", "Port-a-Cath", "Portacath", "Hickman Line", "Hickman", "Broviac Line", "Broviac", "Midline", "Cannula", "Catheter", "Saline", "Heparin", "Flush", "Flushing", "Bolus", "Drip Rate", "Gravity", "Pump", "Syringe Pump", "Infusion Pump", "IVIG", "Total Parenteral Nutrition",
    "Consultation", "Center", "Centre", "Clinic", "Clinics", "Hospital", "Hospitals", "Ward", "Wards", "Unit", "Units", "Department", "Departments", "ER", "ED", "A&E", "ICU", "CCU", "NICU", "PICU", "SICU", "MSU", "Telemetry", "Step Down", "Recovery Room", "OR", "Operating Room", "Theatre", "Theater", "Surgery", "Surgeries", "Surgeon", "Surgeons", "Nurse", "Nurses", "Physician", "Physicians", "Doctor", "Doctors", "GP", "MD", "DO", "PA", "NP", "Therapist", "Therapists", "Pharmacist", "Pharmacists", "Pharmacy", "Pharmacies", "Lab", "Laboratory", "Radiology", "Imaging", "X-ray", "CT Scan", "MRI Scan", "Ultrasound", "Echocardiogram", "ECG", "EEG", "EMG", "Nerve Conduction Study", "Biopsy", "Biopsies", "Pathology", "Pathologist", "Pathologists", "Report", "Reports", "Result", "Results", "Finding", "Findings", "Diagnosis", "Diagnoses", "Prognosis", "Prognoses", 
    "Treatment", "Treatments", "Therapy", "Therapies", "Medication", "Medications", "Drug", "Drugs", "Prescription", "Prescriptions", "Dose", "Doses", "Frequency", "Frequencies", "Duration", "Durations", "Allergy", "Allergies", "Adverse Reaction", "Adverse Reactions", "Side Effect", "Side Effects", "Symptom", "Symptoms", "Sign", "Signs", "Condition", "Conditions", "Disease", "Diseases", "Disorder", "Disorders", "Syndrome", "Syndromes", "Infection", "Infections", "Inflammation", "Inflammations", "Injury", "Injuries", "Trauma", "Fracture", "Fractures", "Burn", "Burns", "Wound", "Wounds", "Healing", "Recovery", "Rehabilitation", "Outcome", "Outcomes", "Complication", "Complications", "Comorbidity", "Comorbidities", "Risk Factor", "Risk Factors", "Prevention", "Screening", "Surveillance", "Monitoring", "Assessments", "Evaluations", "Documentation", "Records", "Charts", "Notes",
    "Provider", "Providers", "Insurance", "Insurances", "Payer", "Payers", "Policy", "Policies", "Plan", "Plans", "Coverage", "Coverages", "Benefit", "Benefits", "Claim", "Claims", "Reimbursement", "Reimbursements", "Billing", "Billings", "Coding", "Codings", "CPT", "ICD-10", "HCPCS", "DRG", "EOB", "Explanation of Benefits", "Pre-Authorization", "Preauthorization", "Referral", "Referrals", "Network", "Networks", "In-Network", "Out-of-Network", "Copay", "Copays", "Deductible", "Deductibles", "Coinsurance", "Premium", "Premiums", "Out-of-Pocket", "OOP", "HSA", "FSA", "HRA", "EOB",
    "Prescribed", "Prescribing", "Prescribes", "Administered", "Administering", "Administers", "Given", "Giving", "Gives", "Taken", "Taking", "Takes", "Used", "Using", "Uses", "Monitored", "Monitoring", "Monitors", "Observed", "Observing", "Observes", "Noted", "Noting", "Notes", "Documented", "Documenting", "Documents", "Recorded", "Recording", "Records", "Reviewed", "Reviewing", "Reviews", "Assessed",
    "Energy", "Heart Rate", "Blood Pressure", "Temperature", "Respiration Rate", "Oxygen Saturation", "Pain Score", "Pain Scale", "Glasgow Coma Scale", "GCS", "BMI", "Body Mass Index", "Weight", "Height", "Head Circumference", "Waist Circumference", "Hip Circumference", "Vision", "Hearing", "Reflexes", "Strength", "Sensation", "Coordination", "Gait", "Balance", "Skin", "Mucous Membranes", "Lymph Nodes",
    "Thyroid", "Heart", "Lungs", "Abdomen", "Extremities", "Neurological Exam", "Neuro Exam", "Mental Status", "Cranial Nerves", "Motor Function", "Sensory Function", "Cerebellar Function", "Gait Assessment", "Reflex Testing", "Fundoscopic Exam", "Ophthalmoscopic Exam", "Ear Exam", "Nasal Exam", "Throat Exam", "Oral Exam", "Dental Exam", "Neck Exam", "Chest Exam", "Cardiac Exam", "Pulmonary Exam", "Abdominal Exam", "Genitourinary Exam", "Rectal Exam", "Musculoskeletal Exam", "Skin Exam", "Dermatological Exam", "Psychiatric Exam", "Mental Health Exam", "Cognitive Exam", "Behavioral Exam", "Emotional Exam", "Mood Assessment", "Affect Assessment", "Thought Process", "Thought Content", "Perception", "Insight", "Judgment", "Risk Assessment", "Safety Assessment", 
    "Renal Ultrasound", "Energy Multifibre", "Heart Multifibre", "Rate Multifibre", "Blood Multifibre", "Pressure Multifibre",
    "Dripfeed Intl", "Patient Referral", "Referral Consultation", "Referral Center", "Referral Centre", "Referral Clinic", "Referral Hospital", "Referral Ward", "Referral Unit", "Referral Department", "Referral ER", "Referral ED", "Referral A&E", "Referral ICU", "Referral CCU", "Referral NICU", "Referral PICU", "Referral SICU", "Referral MSU", "Referral Telemetry", "Referral Step Down", "Referral Recovery Room", "Referral OR", "Referral Operating Room", "Referral Theatre", "Referral Theater", "Referral Surgery", "Referral Surgeon", "Referral Nurse", "Referral Physician", "Referral Doctor",
    "Provider No", "Not Belonging", "The Decameron", "Plan The", "Dear Urology", "Patient Email", "Hounsfield Units", "Urgent Care", "Brazil Bay"


])